### ISSUE TITLE
zmodem 可以使用了吗？

### ISSUE THREAD

**Issue by leffss** [Ri773r/Webterminal#1]
我也做堡垒机，就是xterm.js v4 不支持 zmodem，恼火

**Comment by walirt** [comment]
暂时没有 给zmodem提了issues 作者好像要我提供单元测试 我不会ts 你遇到的问题是啥 加个qq交流一下？

**Comment by leffss** [comment]
xterm.js v4 不支持 zmodem 插件，然后我就找网上 3.14.5 版本使用 zmodem 插件的 demo

我这样写的
```
<script src="https://unpkg.com/xterm@3.14.5/dist/xterm.js"></script>
<script src="https://unpkg.com/xterm@3.14.5/dist/addons/attach/attach.js"></script>
<script src="https://unpkg.com/xterm@3.14.5/dist/addons/webLinks/webLinks.js"></script>
<script src="https://unpkg.com/xterm@3.14.5/dist/addons/fit/fit.js"></script>
<script src="https://unpkg.com/xterm@3.14.5/dist/addons/fullscreen/fullscreen.js"></script>
<script src="https://unpkg.com/xterm@3.14.5/dist/addons/zmodem/zmodem.js"></script>
<script src="https://unpkg.com/xterm@3.14.5/dist/addons/search/search.js"></script>
<script>
        Terminal.applyAddon(attach);
        Terminal.applyAddon(fit);
        Terminal.applyAddon(fullscreen);
        Terminal.applyAddon(search);
        Terminal.applyAddon(webLinks);
        Terminal.applyAddon(zmodem);
        ....
</script>
```

结果浏览器提示 
```
zmodem.ts:90 Uncaught TypeError: Cannot read property 'Browser' of undefined
    at Object.apply (zmodem.ts:90)
    at Function.Terminal.applyAddon (Terminal.ts:181)
    at ws_connect ((index):216)
    at HTMLButtonElement.onclick ((index):94)
```

不知道什么原因呢？！

**Comment by walirt** [comment]
xtermjs4 移除了这个插件 但是这个插件有个单独的仓库 [zmodemjs](https://github.com/FGasper/zmodemjs) 我看别人用xtermjs4+上这个插件也是可以的 但是我的不知道为什么不行 [issuse#10](https://github.com/FGasper/zmodemjs/issues/10)

**Comment by leffss** [comment]
我还是先试试 v3 版本的 zmodem 插件，v3 版本的 xterm.js 就够用了，没必要非用 v4 的，把 v3 的插件搞定了如果有时间可以再来折腾下 v4 的

**Comment by leffss** [comment]
![捕获](https://user-images.githubusercontent.com/49055524/77734828-61da3980-7044-11ea-9705-14ed67826ae0.PNG)

v3 版本的我搞定了

**Comment by walirt** [comment]
你这个后端是python还是go的 给个地址我学习一下

**Comment by leffss** [comment]
https://github.com/leffss/gowebssh ,python 版本的后面来实现

**Comment by leffss** [comment]
https://github.com/leffss/django-webssh ，v4 版本也实现了

**Comment by Lvyc1995** [comment]
> https://github.com/leffss/django-webssh ，v4 版本也实现了

兄弟  6666

**Comment by hessonsu** [comment]
我遇到了跟您一模一样的问题！

**Comment by hessonsu** [comment]
哈哈，我解决了。
 window.zsentry = new Zmodem.Sentry({
                to_terminal: function(octets){},
                sender: function(octets){},
sender 您没有使用websocket 去发送到终端

**Comment by NeroSolomon** [comment]
@leffss 请问你是怎么解决这个问题的？
![image](https://user-images.githubusercontent.com/28894970/114968710-7d132380-9ea9-11eb-81ed-607f2f29078d.png)

**Comment by leffss** [comment]
> @leffss 请问你是怎么解决这个问题的？
> ![image](https://user-images.githubusercontent.com/28894970/114968710-7d132380-9ea9-11eb-81ed-607f2f29078d.png)

自行参考：https://github.com/leffss/gowebssh

**Comment by NeroSolomon** [comment]
> > @leffss 请问你是怎么解决这个问题的？
> > ![image](https://user-images.githubusercontent.com/28894970/114968710-7d132380-9ea9-11eb-81ed-607f2f29078d.png)
> 
> 自行参考：https://github.com/leffss/gowebssh

我就是使用你的repo里的方案，还是有这种问题，想确认一下这个是后端问题还是前端问题呢？

**Comment by NeroSolomon** [comment]
方案是xterm v3.14.5的方案，可以正常监听rz，sz，但输入命令之后就遇到报错

**Comment by leffss** [comment]
> 方案是xterm v3.14.5的方案，可以正常监听rz，sz，但输入命令之后就遇到报错

https://github.com/leffss/gowebssh 中目前使用 xterm v4.8，sz和rz均可正常使用；不保证xterm v3.14.5正确性

**Comment by NeroSolomon** [comment]
@leffss 十分感谢，我先看下v4.8的实现
